# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsIclpoMOSxvlTD57MFrEYu9o33X4Wz7
"""

import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

from pathlib import Path

import torch
import torch.nn as nn
from PIL import Image
from torchvision import models


class CNNEncoder:
    """
    Extract image features using a pretrained ResNet-50.
    """

    def __init__(self, device: torch.device):
        """
        Initialize the pretrained ResNet-50 feature extractor.
        """

        self.device = device

        # Load ResNet-50 pretrained on ImageNet.
        weights = models.ResNet50_Weights.DEFAULT

        self.model = models.resnet50(
            weights=weights
        )

        # Remove the final ImageNet classification layer.
        #
        # Original:
        # 2048 features → 1000 ImageNet classes
        #
        # After replacement:
        # 2048 features → 2048 features
        self.model.fc = nn.Identity()

        # Freeze ResNet because we are using it
        # only as a feature extractor.
        for parameter in self.model.parameters():
            parameter.requires_grad = False

        # Move ResNet to the selected device.
        self.model = self.model.to(self.device)

        # Evaluation mode.
        self.model.eval()

        # Official preprocessing for these ResNet weights.
        self.transform = weights.transforms()

    def extract_batch(
        self,
        image_paths: list[Path],
    ) -> torch.Tensor:
        """
        Extract ResNet-50 features for a batch of images.

        Parameters
        ----------
        image_paths : list[Path]
            Paths to the images.

        Returns
        -------
        torch.Tensor
            Tensor of shape [batch_size, 2048].
        """

        images = []

        for image_path in image_paths:

            try:
                image = Image.open(
                    image_path
                ).convert("RGB")

            except (OSError, ValueError) as error:
                raise ValueError(
                    f"Could not load image: {image_path}"
                ) from error

            # Apply ResNet preprocessing.
            image_tensor = self.transform(image)

            images.append(image_tensor)

        # Combine individual images into one batch.
        #
        # Individual image:
        # [3, 224, 224]
        #
        # Batch:
        # [batch_size, 3, 224, 224]
        batch = torch.stack(images)

        # Move batch to GPU.
        batch = batch.to(self.device)

        # No gradients because ResNet is frozen.
        with torch.no_grad():

            features = self.model(batch)

        # Move features back to CPU before saving.
        return features.cpu()

def cache_features(
    encoder: CNNEncoder,
    image_dir: Path,
    output_dir: Path,
    batch_size: int = 64,
) -> None:
    """
    Extract and cache CNN features for all images.

    Parameters
    ----------
    encoder : CNNEncoder
        ResNet-50 feature extractor.

    image_dir : Path
        Directory containing Flickr8k images.

    output_dir : Path
        Directory where feature files are saved.

    batch_size : int
        Number of images processed by ResNet at once.
    """

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    image_paths = sorted(
        image_dir.glob("*.jpg")
    )

    print(
        f"Found {len(image_paths)} images."
    )

    for start in range(
        0,
        len(image_paths),
        batch_size,
    ):

        batch_paths = image_paths[
            start:start + batch_size
        ]

        features = encoder.extract_batch(
            batch_paths
        )

        for image_path, feature in zip(
            batch_paths,
            features,
        ):

            output_path = (
                output_dir
                / f"{image_path.stem}.pt"
            )

            # Don't overwrite existing features.
            if not output_path.exists():
                torch.save(
                    feature,
                    output_path
                )

        processed = min(
            start + batch_size,
            len(image_paths)
        )

        print(
            f"Processed "
            f"{processed}/{len(image_paths)}"
        )

PROJECT_ROOT = Path("/content/drive/MyDrive")

IMAGE_DIR = PROJECT_ROOT / "Images"

FEATURE_DIR = PROJECT_ROOT / "features"

device = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

print(f"Using device: {device}")

encoder = CNNEncoder(
    device=device
)

cache_features(
    encoder=encoder,
    image_dir=IMAGE_DIR,
    output_dir=FEATURE_DIR,
    batch_size=64,
)